version: '3'
services:
  db:
    image: mysql:latest
    volumes:
     - db:/var/lib/mysql
     - ./resources/sql/setup.sql:/docker-entrypoint-initdb.d
     - /var/run/mysqld/mysqld.sock:/var/run/mysqld/mysqld.sock
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_DATABASE: bbdduniversitat
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysqladmin ping -h localhost -u dev -p dev"
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: dev
    ports:
      - "8091:80"
    depends_on:
      - db


  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8011:8080"
      - "50000:50000"
    volumes:
      - "home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jenkins:/var/jenkins_conf"
    environment:
      JAVA_OPTS: "-Djenkins.install.runSetupWizard=false"
      JENKINS_OPTS: "--prefix=/jenkins"
      TZ: "Europe/Madrid"
    user: root
    depends_on:
      - db
    command: >
      /bin/sh -c '
      curl -L https://get.docker.com | sh;
      usermod -aG docker jenkins;
      apt-get update;
      apt-get install -y maven gradle curl unzip;
      apt-get clean;
      rm -rf /var/lib/apt/lists/*;
      /usr/local/bin/install-plugins.sh docker-plugin workflow-aggregator github-branch-source;
      /sbin/tini -- /usr/local/bin/jenkins.sh;'
volumes:
  mysql_data:
  jenkins_data:
  home:
  db:
